### PR TITLE
Rebase to v2.6.1

### PR DESCRIPTION
**Pull request by RomanBednar**
Diff to upstream v2.6.1:
https://github.com/kubernetes-sigs/vsphere-csi-driver/compare/v2.6.1...RomanBednar:rebase-v2.6.1

Notable changes since v2.6.0:

-  https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/1946

Changelog:
https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.6.1

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
CI can't merge this PR into master, not sure why:

```
CONFLICT (content): Merge conflict in manifests/vanilla/vsphere-csi-driver.yaml
Auto-merging manifests/vanilla/validatingwebhook.yaml
CONFLICT (content): Merge conflict in manifests/vanilla/validatingwebhook.yaml
Automatic merge failed; fix conflicts and then commit the result.
# Error: exit status 1
```

**Comment by duanwei33** [comment]
From my understanding, this is not needed in OCP or regression test could cover it somehow? 
> Support improved idempotency feature when the vSphere CSI driver is running in a different namespace, other than vmware-system-csi

I performed regression tests with rebased CSI Driver, looks good. 

/label qe-approved

**Comment by jsafrane** [comment]
/label docs-approved
/label px-approved
We don't document CSI driver rebases in OCP

**Pull request merged**
