### PR TITLE
 Merge changes from v2.4.0 upstream tag

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage 

https://github.com/kubernetes-sigs/vsphere-csi-driver/compare/v2.4.0..bertinatto:merge-v2.4.0

For some reason the link above doesn't show the changed files. That can be done with:

```
$ git diff v2.4.0..merge-v2.4.0 --stat
 .ci-operator.yaml                                  |      4 +
 .gitignore                                         |      6 -
 Dockerfile.openshift                               |     12 +
 Dockerfile.syncer.openshift                        |      8 +
 Makefile                                           |     15 +-
 OWNERS                                             |     25 +-
 OWNERS_ALIASES                                     |      7 +
 go.mod                                             |      1 -
 go.sum                                             |      5 -
 vendor/github.com/Azure/go-ansiterm/LICENSE        |     21 +
 vendor/(...)
 5996 files changed, 2102926 insertions(+), 41 deletions(-)
```

### CODE REVIEW

**Comment by jsafrane** [comment]
/retitle WIP: Merge changes from v2.4.0 upstream tag

**Comment by bertinatto** [comment]
`e2e-vsphere-csi-migration` failed with the usual suspects:

```
[sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Inline-volume (default fs)] volumes should store data [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Inline-volume (ext4)] volumes should store data [Suite:openshift/conformance/parallel] [Suite:k8s]
```

Running everything over again just in case:
/test all

**Pull request merged**
