### PR TITLE
Rebase v2.3.0 rc.3

### PR DESCRIPTION
**Pull request by bertinatto**
https://github.com/kubernetes-sigs/vsphere-csi-driver/compare/v2.3.0-rc.3...bertinatto:rebase-v2.3.0-rc.3

I'm not sure why openshift/vmware-vsphere-csi-driver@master has so many additional commits that are not present in kubernetes-sigs/vsphere-csi-driver. For instance:

https://github.com/kubernetes-sigs/vsphere-csi-driver/commit/87bdb73cf21f2136444112d4de96cc0c243bee4c

It could be something from a previous rebase?

@jsafrane @gnufied please review carefully. I'll add an hold to avoid merging accidentally. 

Edit: seems like images are not building, I'll have a look tomorrow.

/hold
CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold cancel
I tested PR along with https://github.com/openshift/cluster-storage-operator/pull/188 and https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/32. No noticeable issues.

**Comment by gnufied** [comment]
I tested this PR manually also and only issue I found is - if you upgrade the driver then newly introduced permissions aren't applied and nodes still can't fetch configmaps. Deleting the clusterrolebinding however solved that issue and operator automatically created a new clusterolebinding with correct permissions.

**Pull request merged**
