### PR TITLE
Bug 2067889: Rebase driver on v2.7.0

### PR DESCRIPTION
**Pull request by dobsonj**
https://bugzilla.redhat.com/show_bug.cgi?id=2067889
There is a new release v2.7.0 now, so I just did a rebase to avoid cherry-pick.
https://github.com/kubernetes-sigs/vsphere-csi-driver/compare/v2.7.0...dobsonj:bug2067889
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
I see just volume expansion failures due to https://issues.redhat.com/browse/OCPBUGS-2927, which should be fixed by https://github.com/openshift/kubernetes/pull/1402 now
/retest

**Comment by dobsonj** [comment]
`Failed to download metadata for repo 'rhel-8-baseos'`
/retest

**Comment by jsafrane** [comment]
/override ci/prow/e2e-vsphere

We're fixing the tests in https://github.com/openshift/origin/pull/27565

**Pull request merged**
