### PR TITLE
STOR-863: Rebase to v2.6.0

### PR DESCRIPTION
**Pull request by RomanBednar**
Diff to upstream v2.6.0:
https://github.com/kubernetes-sigs/vsphere-csi-driver/compare/v2.6.0...RomanBednar:rebase-v2.6.0

Notable changes since v2.5.1:

- Enhanced Volume Topology 
- Support migration of in-tree vSphere PVs with legacy topology labels
- Support RWX PV provisioning on remote vSAN
- Support running vSphere Container Storage Plug-in on a different Kubernetes cluster

Changelog:
https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.6.0

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
> https://github.com/kubernetes-sigs/vsphere-csi-driver/compare/v2.6.0...RomanBednar:rebase-v2.6.0

Why are there changes in pkg/csi/service/common/common_controller_helper.go  and pkg/csi/service/vanilla/controller.go? Even compiler does not like them.

**Comment by RomanBednar** [comment]
> > [kubernetes-sigs/vsphere-csi-driver@v2.6.0...RomanBednar:rebase-v2.6.0](https://github.com/kubernetes-sigs/vsphere-csi-driver/compare/v2.6.0...RomanBednar:rebase-v2.6.0)
> 
> Why are there changes in pkg/csi/service/common/common_controller_helper.go and pkg/csi/service/vanilla/controller.go? Even compiler does not like them.

Merge strategy caused duplicates and I missed that. Trying different approach.

**Comment by jsafrane** [comment]
@RomanBednar I missed invalid OWNERS error, please clean that up (delete or update offending OWNERS in the first `<carry>` patch.

**Comment by RomanBednar** [comment]
> @RomanBednar I missed invalid OWNERS error, please clean that up (delete or update offending OWNERS in the first `<carry>` patch.

@jsafrane ack, removing e2e tests OWNERS file

**Comment by duanwei33** [comment]
Pre-merge verified passed with regression test, no issue found.
For the new Volume Topology feature, will test it in 4.12 new feature.

/label qe-approved

**Comment by jsafrane** [comment]
/label docs-approved
/label px-approved

We don't document / announce CSI driver version bumps to customers.

**Pull request merged**
