### PR TITLE
Bug 2071019: Rebase against v2.5.1

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2071019

Diff https://github.com/kubernetes-sigs/vsphere-csi-driver/compare/v2.5.1...gnufied:upstream-v251

### CODE REVIEW

**Comment by gnufied** [comment]
The failure here looks like those coming from - https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/1653

**Comment by bertinatto** [comment]
Changelog: https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.5/rn/vmware-vsphere-container-storage-plugin-25-release-notes/index.html

**Comment by bertinatto** [comment]
@gnufied lgtm, but you might want to run `go mod vendor` again (for me it changes the ./vendor).

**Comment by bertinatto** [comment]
BTW, both driver & syncer are exposing metrics now [1], so we could start scraping them in 4.11.

[1] https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-65817276-3F34-4E45-92A0-831316AEC853.html

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
