### PR TITLE
OCPBUGS-24716: Revert "STOR-1396: Rebase to v3.1.1 for OCP 4.15"

### PR DESCRIPTION
**Pull request by gnufied**
Reverts openshift/vmware-vsphere-csi-driver#97

I didn't do anything fancy to revert these changes. I simply pressed the revert button on Github which typically is displayed on a merged PR. 

Just for comparison - I also did a manual revert on CLI using following command:

```
git revert -m1 <merge_sha>
```

And contents were identical to one produced in this PR.

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by jsafrane** [comment]
/override ci/prow/e2e-vsphere-ovn-upgrade
because of https://issues.redhat.com/browse/OCPBUGS-25431

**Pull request merged**
