### PR TITLE
STOR-1396: Rebase to v3.1.1 for OCP 4.15

### PR DESCRIPTION
**Pull request by jsafrane**
Diff to upstream v3.1.1:
https://github.com/kubernetes-sigs/vsphere-csi-driver/compare/v3.1.1...jsafrane:rebase-v3.1.1

Full changelogs since v3.0.2 that we have in 4.14:
* 3.1.1: https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v3.1.1
* 3.1.0: https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v3.1.0

Notable changes:
* vSAN HCI Mesh support for CNS block volumes. Refer to [documentation](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-3837AE1E-B31B-44BA-B0B0-643F776ACDB9.html) for detail.
* Added resize capability for migrated in-tree vSphere volumes. (I am not sure we want to support this... But it can't be turned off)

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/override ci/prow/e2e-vsphere-csi
this is expected to fail on rebases

**Comment by Phaow** [comment]
Hi @jsafrane , it seems need to override `ci/prow/verify-commits`.

**Pull request merged**
